version: "3.9"
services:
  api:
    container_name: dev1
    build: ./dev1/
    ports:
      - "5000:5000"
    volumes:
      - type: volume
        source: dev1-vol
        target: /app 
  nodered:
    container_name: nodered
    build: ./nodered/ 
    ports:
      - "1880:1880"
    volumes:
      - type: volume
        source: nodered-vol
        target: /data
    environment:
      - INFLUXDB_TOKEN=hamzatoken
  influxdb:
    container_name: influxdb  
    build: ./influxdb/
    ports:
      - "8086:8086"
    volumes:
      - type: volume
        source: influxdb-vol
        target: /var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup 
      - DOCKER_INFLUXDB_INIT_USERNAME=hamza
      - DOCKER_INFLUXDB_INIT_PASSWORD=noweder@1234
      - DOCKER_INFLUXDB_INIT_ORG=noweder
      - DOCKER_INFLUXDB_INIT_BUCKET=noweder-bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=hamzatoken
  grafana:
    container_name: grafana
    build: ./grafana
    ports:
      - "3000:3000"
    volumes:
      - type: volume
        source: grafana-vol
        target: /var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=hamza
      - GF_SECURITY_ADMIN_PASSWORD=noweder@1234
volumes:
  dev1-vol: {}
  nodered-vol: {}
  influxdb-vol: {}
  grafana-vol: {}
  