version: "3.9"
services:
  api:
    container_name: dev1
    build: ./dev1/
    networks:
      - backend
    volumes:
      - type: volume
        source: dev1-vol
        target: /app 
  nodered:
    container_name: nodered
    build: ./nodered/
    networks:
      - backend
    ports:
      - "1880:1880"
    volumes:
      - type: volume
        source: nodered-vol
        target: /data
    environment:
      - INFLUXDB_TOKEN=hamzatoken
  influxdb:
    container_name: influxdb  
    build: ./influxdb/
    networks:
      - backend
    volumes:
      - type: volume
        source: influxdb-vol
        target: /var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup 
      - DOCKER_INFLUXDB_INIT_USERNAME=hamza
      - DOCKER_INFLUXDB_INIT_PASSWORD=noweder@1234
      - DOCKER_INFLUXDB_INIT_ORG=noweder
      - DOCKER_INFLUXDB_INIT_BUCKET=noweder-bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=hamzatoken
  grafana:
    container_name: grafana
    build: ./grafana/
    networks:
      - frontend
      - backend
      - postgres-db
    ports:
      - "3000:3000"
    volumes:
      - type: volume
        source: grafana-vol
        target: /var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=hamza
      - GF_SECURITY_ADMIN_PASSWORD=noweder@1234
      - INFLUXDB_TOKEN=hamzatoken
      - POSTGRES_USER=hamza
      - POSTGRES_DB=noweder-db
      - POSTGRES_PASSWORD=noweder1234
  postgres:
    container_name: postgres
    build: ./postgres/
    networks:
      - postgres-db
    volumes:
      - type: volume
        source: postgres-vol
        target: /var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hamza
      - POSTGRES_PASSWORD=noweder1234
      - POSTGRES_DB=noweder-db
  postgrest:
    container_name: postgrest
    image: postgrest/postgrest
    networks:
      - backend
      - postgres-db
    environment:
      - PGRST_DB_URI=postgres://hamza:noweder1234@postgres:5432/noweder-db
      - PGRST_DB_ANON_ROLE=hamza
      - PGRST_DB_SCHEMA=public
volumes:
  dev1-vol: {}
  nodered-vol: {}
  influxdb-vol: {}
  grafana-vol: {}
  postgres-vol: {}
networks:
  frontend: {}
  backend: {}
  postgres-db: {}
  